# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(300, 300))
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setDefaultSectionSize(200)
        self.treeView.header().setMinimumSectionSize(150)
        self.treeView.header().setStretchLastSection(False)
        self.verticalStackedWidget = QtWidgets.QStackedWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalStackedWidget.sizePolicy().hasHeightForWidth())
        self.verticalStackedWidget.setSizePolicy(sizePolicy)
        self.verticalStackedWidget.setMinimumSize(QtCore.QSize(320, 0))
        self.verticalStackedWidget.setObjectName("verticalStackedWidget")
        self.verticalStackedWidgetPage1 = QtWidgets.QWidget()
        self.verticalStackedWidgetPage1.setObjectName("verticalStackedWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalStackedWidgetPage1)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalStackedWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 0))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.albumArtLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.albumArtLabel.sizePolicy().hasHeightForWidth())
        self.albumArtLabel.setSizePolicy(sizePolicy)
        self.albumArtLabel.setMinimumSize(QtCore.QSize(120, 120))
        self.albumArtLabel.setMaximumSize(QtCore.QSize(120, 120))
        self.albumArtLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.albumArtLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.albumArtLabel.setText("")
        self.albumArtLabel.setScaledContents(True)
        self.albumArtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.albumArtLabel.setObjectName("albumArtLabel")
        self.gridLayout.addWidget(self.albumArtLabel, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDuration = QtWidgets.QLabel(self.groupBox)
        self.labelDuration.setObjectName("labelDuration")
        self.verticalLayout_2.addWidget(self.labelDuration)
        self.labelSampleRate = QtWidgets.QLabel(self.groupBox)
        self.labelSampleRate.setObjectName("labelSampleRate")
        self.verticalLayout_2.addWidget(self.labelSampleRate)
        self.labelChannels = QtWidgets.QLabel(self.groupBox)
        self.labelChannels.setObjectName("labelChannels")
        self.verticalLayout_2.addWidget(self.labelChannels)
        self.labelBitrate = QtWidgets.QLabel(self.groupBox)
        self.labelBitrate.setObjectName("labelBitrate")
        self.verticalLayout_2.addWidget(self.labelBitrate)
        self.labelCodec = QtWidgets.QLabel(self.groupBox)
        self.labelCodec.setObjectName("labelCodec")
        self.verticalLayout_2.addWidget(self.labelCodec)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalStackedWidgetPage1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalStackedWidget.addWidget(self.verticalStackedWidgetPage1)
        self.verticalStackedWidgetPage2 = QtWidgets.QWidget()
        self.verticalStackedWidgetPage2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalStackedWidgetPage2.setObjectName("verticalStackedWidgetPage2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalStackedWidgetPage2)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bigAlbumArtLabel = QtWidgets.QLabel(self.verticalStackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bigAlbumArtLabel.sizePolicy().hasHeightForWidth())
        self.bigAlbumArtLabel.setSizePolicy(sizePolicy)
        self.bigAlbumArtLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.bigAlbumArtLabel.setMaximumSize(QtCore.QSize(300, 300))
        self.bigAlbumArtLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.bigAlbumArtLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bigAlbumArtLabel.setText("")
        self.bigAlbumArtLabel.setScaledContents(True)
        self.bigAlbumArtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bigAlbumArtLabel.setObjectName("bigAlbumArtLabel")
        self.verticalLayout_3.addWidget(self.bigAlbumArtLabel)
        self.listWidget = QtWidgets.QListWidget(self.verticalStackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setIconSize(QtCore.QSize(120, 120))
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalStackedWidget.addWidget(self.verticalStackedWidgetPage2)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOnline = QtWidgets.QMenu(self.menubar)
        self.menuOnline.setObjectName("menuOnline")
        MainWindow.setMenuBar(self.menubar)
        self.actionSelectFolder = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectFolder.setIcon(icon)
        self.actionSelectFolder.setObjectName("actionSelectFolder")
        self.actionTagToFile = QtWidgets.QAction(MainWindow)
        self.actionTagToFile.setObjectName("actionTagToFile")
        self.actionFileToTag = QtWidgets.QAction(MainWindow)
        self.actionFileToTag.setObjectName("actionFileToTag")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionDeleteTag = QtWidgets.QAction(MainWindow)
        self.actionDeleteTag.setObjectName("actionDeleteTag")
        self.actionRevertFile = QtWidgets.QAction(MainWindow)
        self.actionRevertFile.setObjectName("actionRevertFile")
        self.actionFolderByTag = QtWidgets.QAction(MainWindow)
        self.actionFolderByTag.setObjectName("actionFolderByTag")
        self.actionGetOnlineTags = QtWidgets.QAction(MainWindow)
        self.actionGetOnlineTags.setObjectName("actionGetOnlineTags")
        self.actionCreateFolder = QtWidgets.QAction(MainWindow)
        self.actionCreateFolder.setObjectName("actionCreateFolder")
        self.actionLevelUp = QtWidgets.QAction(MainWindow)
        self.actionLevelUp.setObjectName("actionLevelUp")
        self.actionPutTagsOnline = QtWidgets.QAction(MainWindow)
        self.actionPutTagsOnline.setObjectName("actionPutTagsOnline")
        self.actionSpectogram = QtWidgets.QAction(MainWindow)
        self.actionSpectogram.setObjectName("actionSpectogram")
        self.actionSetRootDir = QtWidgets.QAction(MainWindow)
        self.actionSetRootDir.setObjectName("actionSetRootDir")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.toolBar.addAction(self.actionSelectFolder)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionCreateFolder)
        self.toolBar.addAction(self.actionSetRootDir)
        self.toolBar.addAction(self.actionLevelUp)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionTagToFile)
        self.toolBar.addAction(self.actionFileToTag)
        self.toolBar.addAction(self.actionDeleteTag)
        self.toolBar.addAction(self.actionRevertFile)
        self.toolBar.addAction(self.actionFolderByTag)
        self.toolBar.addAction(self.actionGetOnlineTags)
        self.toolBar.addAction(self.actionPutTagsOnline)
        self.toolBar.addAction(self.actionSpectogram)
        self.menuFile.addAction(self.actionSelectFolder)
        self.menuFile.addAction(self.actionCreateFolder)
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionDelete)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionTagToFile)
        self.menuTools.addAction(self.actionFileToTag)
        self.menuTools.addAction(self.actionFolderByTag)
        self.menuTools.addAction(self.actionRevertFile)
        self.menuTools.addAction(self.actionDeleteTag)
        self.menuTools.addAction(self.actionSpectogram)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOnline.addAction(self.actionGetOnlineTags)
        self.menuOnline.addAction(self.actionPutTagsOnline)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOnline.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.verticalStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TikTag v1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "General"))
        self.labelDuration.setText(_translate("MainWindow", "Duration: "))
        self.labelSampleRate.setText(_translate("MainWindow", "Sample Rate:"))
        self.labelChannels.setText(_translate("MainWindow", "Channels:"))
        self.labelBitrate.setText(_translate("MainWindow", "Bitrate:"))
        self.labelCodec.setText(_translate("MainWindow", "Codec:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Metadata"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuOnline.setTitle(_translate("MainWindow", "Online"))
        self.actionSelectFolder.setText(_translate("MainWindow", "SelectFolder"))
        self.actionTagToFile.setText(_translate("MainWindow", "TagToFile"))
        self.actionFileToTag.setText(_translate("MainWindow", "FileToTag"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDeleteTag.setText(_translate("MainWindow", "DeleteTag"))
        self.actionRevertFile.setText(_translate("MainWindow", "RevertFile"))
        self.actionFolderByTag.setText(_translate("MainWindow", "FolderByTag"))
        self.actionGetOnlineTags.setText(_translate("MainWindow", "GetOnlineTags"))
        self.actionCreateFolder.setText(_translate("MainWindow", "CreateFolder"))
        self.actionLevelUp.setText(_translate("MainWindow", "LevelUp"))
        self.actionPutTagsOnline.setText(_translate("MainWindow", "PutTagsOnline"))
        self.actionSpectogram.setText(_translate("MainWindow", "Spectogram"))
        self.actionSetRootDir.setText(_translate("MainWindow", "SetRootDir"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))


import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
